const AboutPage = () => {
  // return <div>  About Page</div>
  return (
    <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque quam dolor, pretium ac mattis feugiat, commodo non lorem. Fusce cursus dignissim lectus, sit amet fermentum leo pulvinar at. Suspendisse varius enim eu metus rutrum, sit amet faucibus sem egestas. Maecenas blandit, quam sed bibendum efficitur, ante ligula rhoncus tortor, id tempus metus erat nec quam. Sed sed mi purus. Maecenas viverra quam ex, ut sodales magna commodo semper. Proin fringilla ligula auctor, blandit lorem ut, sodales libero. Nam convallis arcu vitae lorem molestie eleifend. Vestibulum consequat erat quis ligula ultricies imperdiet. Aenean ultricies pretium scelerisque.
        Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas posuere felis non dignissim pellentesque. Ut sollicitudin efficitur diam ut elementum. Aenean faucibus, urna at dapibus pellentesque, eros elit molestie felis, in volutpat nisl odio eget dui. Morbi interdum maximus mattis. Ut a viverra nulla, sit amet faucibus dui. Etiam sed tortor quis tellus venenatis tempus at sit amet sapien. Ut suscipit rhoncus condimentum. Quisque pharetra magna eu purus mollis imperdiet. Donec non nisi facilisis, tempor mi id, commodo ipsum.
        Pellentesque vulputate enim et ligula egestas, ut faucibus odio vestibulum. Nulla eget enim magna. Aenean ut imperdiet libero, vel imperdiet eros. Etiam mi nibh, elementum non metus sed, volutpat mattis massa. Quisque eget enim a turpis viverra faucibus iaculis eget erat. Sed fringilla elit a elit fermentum, vitae lobortis ante sodales. Nullam condimentum pretium varius. Integer eu diam auctor, semper ex eget, sagittis dui. Nullam erat nisl, tincidunt at facilisis vitae, iaculis non nibh. Mauris rhoncus fringilla quam, tincidunt mollis turpis consectetur laoreet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum, eros efficitur aliquam viverra, est mi lacinia odio, non placerat neque massa vitae mi. Proin scelerisque lacus sed ornare egestas. In ultrices tellus ut nulla volutpat, a lacinia tortor dignissim.
        Phasellus tristique ligula in purus auctor pretium. Aenean volutpat odio massa, id volutpat nunc sollicitudin nec. Cras nisi metus, sollicitudin a rutrum sit amet, interdum id dui. Sed tempor volutpat porttitor. Phasellus nec dolor sed velit vulputate bibendum. Sed ultricies, velit aliquam dictum mattis, ante dui accumsan ex, quis vestibulum justo sem ac justo. Maecenas consectetur suscipit convallis. Phasellus tristique tincidunt velit, et luctus arcu mollis non. Aenean neque justo, convallis vel purus nec, vehicula vulputate augue. Duis sed tortor eget elit vehicula ultricies. Vivamus fringilla enim sem, vitae sodales tellus tincidunt ut.
        Quisque eu congue orci, quis feugiat lacus. Duis elementum convallis arcu quis mollis. Vestibulum euismod purus et pellentesque pretium. Vestibulum pellentesque sollicitudin vestibulum. Duis nunc velit, elementum ut elementum a, efficitur varius lectus. Curabitur suscipit ultricies blandit. Duis nec velit non velit egestas pellentesque. Integer tincidunt suscipit purus. Vivamus finibus dolor quam, non consectetur nunc porta a.
        Sed semper et odio at eleifend. Cras eget congue nunc. Aenean lobortis urna nibh, sit amet blandit dolor sodales in. Pellentesque rutrum semper odio eu gravida. Proin tempus sem at sem dictum facilisis. Quisque eleifend turpis eu mi accumsan tincidunt. Integer eu consectetur tellus, sed dictum mauris. Ut enim arcu, ultricies at justo at, malesuada lacinia ex. Ut tempor sagittis enim mollis efficitur. Aenean quis sapien tristique, dignissim dolor nec, aliquam metus. Mauris ullamcorper diam sed pellentesque ultrices. Mauris mollis diam facilisis ligula pretium eleifend. Donec vehicula convallis ullamcorper. Pellentesque lacinia nulla non massa vehicula, eu tempor ante sagittis.
        Nullam tincidunt felis ac bibendum blandit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce ut elit in nisl aliquam posuere. Nulla vitae accumsan nunc. Quisque sit amet dolor lacus. Cras pellentesque laoreet ligula, sagittis volutpat metus sagittis sed. Duis nec consequat arcu. Integer rutrum at velit sed cursus. Fusce bibendum, nisi vel dapibus pellentesque, mi erat fermentum ligula, faucibus mattis purus felis et quam. Nullam ut vulputate arcu.
        Vestibulum nec tortor laoreet, molestie dui a, imperdiet felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi posuere erat nec lobortis dignissim. Etiam nec ultricies lectus. Curabitur non erat nec ex elementum egestas nec quis lectus. Nulla in tortor vitae purus posuere accumsan. Integer placerat diam faucibus urna auctor facilisis. Vivamus nec sem nec metus malesuada venenatis. Quisque lobortis odio vitae sagittis luctus.
        Aliquam venenatis nunc eu enim efficitur bibendum. Proin varius eros sit amet rutrum aliquam. Mauris vestibulum lectus vel neque commodo vehicula. Aenean vitae nisl arcu. Sed lorem urna, varius quis mollis eget, viverra sed nulla. Aliquam semper velit justo, id dignissim ex fringilla at. Etiam est urna, tempor id tincidunt volutpat, porttitor ac nunc. Morbi non metus nunc. Integer dapibus hendrerit mi vel tempus. Vestibulum ultricies tellus nec tincidunt tincidunt. Proin faucibus, purus sed lacinia sollicitudin, justo tellus pulvinar dolor, ac commodo urna ipsum eu massa.
        Aenean dapibus bibendum elit, eu pellentesque turpis molestie vitae. Nullam placerat ut diam nec sodales. Quisque nec turpis turpis. Quisque quis sodales ex. Praesent dignissim euismod metus. Sed ultrices urna sed lorem malesuada, eget maximus tellus pulvinar. Quisque laoreet pellentesque purus, nec porttitor nibh sollicitudin ut. Sed ut gravida mi. Nam malesuada vel velit eu hendrerit. Curabitur tempus quam eget nibh tincidunt mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam auctor lacus sodales, tristique dui eu, molestie augue.
        Nam at nisl in sapien scelerisque lacinia ut et metus. Donec eget sem ligula. Sed gravida, ante quis sagittis rhoncus, orci felis condimentum nisi, ut pellentesque neque leo at libero. Sed eleifend tempor est vitae sodales. Integer ut purus nisi. Sed ornare euismod dui quis congue. Donec faucibus, risus quis convallis pretium, risus libero vulputate ex, a molestie augue mauris eget mauris. Mauris volutpat, est sit amet suscipit varius, lectus magna convallis magna, et congue augue est a nibh. Vivamus hendrerit faucibus ultricies. Vestibulum aliquet metus sapien, et dictum lectus interdum et. Sed auctor bibendum nunc, eu elementum eros placerat nec. Nam ac diam vestibulum, venenatis metus quis, gravida enim. Ut vitae felis sagittis, vulputate ligula ut, tincidunt tellus. Morbi malesuada massa id porttitor consectetur. Proin blandit elit nisi, lobortis dignissim urna iaculis non. Etiam pellentesque odio in eros pellentesque, ac commodo mi ullamcorper.
        Morbi gravida vitae turpis et fermentum. Curabitur a aliquam ante. Mauris a sem lacus. In nisl arcu, maximus eu nisi in, bibendum euismod sapien. Proin pretium sapien egestas ante vulputate, in luctus turpis feugiat. Pellentesque ut risus vel metus efficitur fermentum. Ut non augue congue lacus viverra efficitur vel in urna.
        Aliquam condimentum nunc a venenatis sollicitudin. Praesent tincidunt ex non tempus lacinia. Aliquam erat volutpat. Praesent dapibus nunc eget hendrerit pharetra. Maecenas ac lobortis lacus. Aliquam egestas in odio ac viverra. In nec ipsum ac lacus dignissim malesuada vel nec quam. Vestibulum pulvinar arcu nec diam pulvinar pharetra. Mauris finibus pellentesque enim quis eleifend. Vestibulum sit amet leo et augue volutpat imperdiet. Cras tincidunt lobortis vestibulum. Nunc efficitur, velit et placerat sodales, dui dolor pharetra libero, sit amet egestas magna erat non justo. Morbi sit amet faucibus nulla.
        Maecenas ullamcorper neque arcu. Aenean commodo mollis magna, ut pulvinar nisl pretium eu. Pellentesque sit amet dui purus. Phasellus eget tortor ut lacus maximus maximus a quis tellus. Quisque vitae feugiat dolor. Cras nec purus orci. Suspendisse ligula diam, scelerisque eu interdum vel, rutrum eu risus. Aenean vel vulputate felis, laoreet volutpat lectus. Cras a scelerisque ex.
        In ut bibendum nulla. Nam convallis ante eget viverra hendrerit. Etiam id molestie sem, vel pulvinar augue. Mauris tincidunt enim dolor, eu elementum ipsum lobortis at. Vestibulum sed interdum lacus. In id turpis ac orci imperdiet pharetra vestibulum varius est. Maecenas eu nibh ante. Pellentesque imperdiet dolor et imperdiet imperdiet. Aenean suscipit purus quis fringilla lacinia. Nullam vestibulum nunc quis ullamcorper placerat. Morbi suscipit finibus dignissim. Phasellus et tellus purus. Vestibulum vitae ex nisi. Cras ullamcorper risus vulputate tellus aliquam auctor.
        Suspendisse consectetur felis nibh, sed molestie arcu vulputate sagittis. Nam lacus nulla, ornare sed eros vitae, sodales tincidunt elit. Vestibulum sagittis iaculis orci, posuere malesuada turpis porta egestas. Vestibulum venenatis tellus eget lectus pulvinar lobortis. Donec nisi elit, dapibus quis neque a, aliquet volutpat odio. Etiam dui est, auctor non vehicula vitae, auctor sed augue. Aliquam tempus maximus sapien, sed consequat enim placerat venenatis. Suspendisse eleifend massa sem, id venenatis sapien pretium non. Maecenas nisi magna, pellentesque non lectus vel, sollicitudin volutpat urna.
        Proin a nulla urna. Nullam id suscipit eros. Quisque commodo iaculis leo, ut egestas enim posuere vitae. Aenean eget nunc nibh. In eu massa ut erat pharetra porta congue in orci. Quisque eget nisl ornare, tristique neque a, scelerisque est. Donec tincidunt porta massa, et interdum libero. Vestibulum non tincidunt ex. Nulla vitae tortor eget orci porttitor mollis sed nec sem.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vehicula turpis quis tortor ultrices, non convallis risus pulvinar. Etiam eget commodo dui, id semper leo. Quisque vitae fermentum eros. Aenean sit amet lacus nibh. Proin faucibus orci convallis mi lobortis, vel mattis urna interdum. Aliquam quis iaculis odio. Pellentesque sagittis, magna sed congue pretium, arcu libero maximus mi, id rutrum urna risus ac velit. Mauris ornare mi sed nisi cursus, vel ultrices sapien accumsan. Donec vel velit vitae leo mollis tincidunt sed non leo. Aliquam cursus maximus neque nec efficitur.
        Aenean venenatis nisi at luctus tempor. Vestibulum ac arcu molestie, consequat lorem a, sollicitudin dolor. Curabitur metus mauris, vehicula at auctor in, sodales id augue. Mauris dui erat, pulvinar a felis nec, vestibulum dignissim lacus. Duis ipsum ligula, imperdiet et auctor sit amet, ornare in lorem. Maecenas facilisis dolor eget condimentum fermentum. Nulla porttitor, odio et mollis tristique, ante risus tempus nibh, non gravida arcu purus sit amet tortor.
        Ut tristique nulla dolor, vitae iaculis sapien mattis a. Pellentesque fermentum fermentum consectetur. Vivamus molestie lacus in cursus egestas. Fusce ultrices augue vitae elementum accumsan. Integer ipsum sapien, sollicitudin vel sem vitae, auctor mattis dui. In rhoncus ac tellus egestas egestas. Donec dapibus porta fermentum. Ut tempus, ex in euismod posuere, quam enim facilisis augue, sit amet hendrerit ante metus sit amet ex. Ut vitae vehicula sem. Donec eu consequat libero, a sagittis ligula. Suspendisse dignissim dictum lorem sit amet rhoncus. Vivamus sed justo nec velit euismod varius. 
    </div>
  )
}

export default AboutPage;



